# available modules
# "netspeed", "memory", "cpu", "weather", "time", "battery"
format = "{datetime}"

# get your api key from:
# https://openweathermap.org/
weather_apikey = ""
weather_city = ""

# network interface ($ ip addr show)
net_interface = "eno1"

# update interval in seconds
update_interval = 1
