output_separator = " "

# available modules
# "netspeed", "memory", "cpu", "weather", "time", "battery"
output_order = [
	"netspeed",
	"memory",
	"cpu",
	"battery",
	"weather",
	"time",
]

# get your api key from:
# https://openweathermap.org/
weather_apikey = ""
weather_city = ""

# network interface ($ ip addr show)
net_interface = "eno1"

# update interval in seconds
update_interval = 1
